spring.application.name=ExcelRMay2026BatchSpringboot
server.port=8090
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Wipro@123