spring.application.name=ExcelRMay2026BatchSpringboot
server.port=8090
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/excelrjuly2026db
spring.datasource.username=postgres
spring.datasource.password=Wipro@123
spring.jpa.hibernate.ddl-auto=create

MySQL 
#server.port=8085
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/itpaugspringbootdb-local
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update


